version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public
      - ./.next/static:/app/.next/static
    depends_on:
      - app

  pm2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/usr/local/bin/pm2-runtime", "ecosystem.config.js"]
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - nginx
      - app